### ISSUE TITLE
希望支持文件夹嵌套

### ISSUE THREAD

**Issue by jiangjunfeng98** [wangxing218/apite#1]
apite 使用体验非常棒，如果支持文件嵌套就完美了。

RT，实际项目中希望对mock数据进行归类，目前好像不支持。

- apite：1.2.5

## 目录结构

```shell
- mocks
   - tickets
      - home.js
   - user.js 
```

这个嵌套识别不了 home.js 中的 mock 数据，需要将 home.js 移到外层才可以

**Comment by wangxing218** [comment]
下个版本会考虑实现

**Comment by wangxing218** [comment]
1.3.0版本已发布，支持文件夹嵌套
