### ISSUE TITLE
配置多个prefix

### ISSUE THREAD

**Issue by MrTibbles2019** [wangxing218/apite#10]
如果我想同时配置 /api/project，/api/template，应该如何配置

**Comment by wangxing218** [comment]
统一配置为 prefix: '/api'， 
再在mock接口里自行加上前辍
如 api.get('/project/xxx',{})

**Comment by MrTibbles2019** [comment]
> 统一配置为 prefix: '/api'， 再在mock接口里自行加上前辍 如 api.get('/project/xxx',{})

感谢大佬的回复。还有一个问题望解答。
我使用脚手架vite，在vite.config.ts中做了如下配置，在配置中设置了”mock：false“不使用全局代理。但是实际接口请求时，并没有复合预期：“在mock接口声明过的走mock；其他则走proxy代理"；而是被mock过的走mock，其他请求则为404。
`
{
  server: {
        host: '0.0.0.0',
        open: true, //设置服务启动时是否自动打开浏览器
        cors: true, // 默认启用并允许任何源
        https: false,
        hmr: true,
        //设置代理
        proxy: {
          '/api': {
            target: 'http://127.0.0.1:12420',
            changeOrigin: true,
            rewrite: (path) => path.replace('/api', '/')
          }
        }
  },
  plugins: [
       vite2Ext({
          dir: 'mock',
          mock: false,
          prefix: '/api'
        }) as any,
  ]
}
`

**Comment by wangxing218** [comment]
server.proxy代理与mock的前辍设置成一样的会有问题，你可以把server.proxy本身的代理去掉，在接口里随时申明代理即可，
`
// mock/proxy.js
module.exports = {
    local: {
        proxy: 'http://127.0.0.1:12420'
    },
    dev: {
        proxy: 'http://127.0.0.1:12421'
    }
};


// mock/api.js
const {api, resp} = require('apite');
const proxy = require('./proxy');
/**
 * 走代理，修改后可实时生效
 */
api.post('/account/updateInfo', async ctx=>{
    ctx.body = resp.ok();
}, proxy.dev);

/**
 * 不走代理，第三个参数为false即可
 */
api.post('/account/updateInfo', async ctx=>{
    ctx.body = resp.ok();
}, proxy.dev11);
`

**Comment by wangxing218** [comment]
server.proxy代理与mock的前辍设置成一样的会有问题，你可以把server.proxy本身的代理去掉，在接口里随时申明代理即可，
```js
// mock/proxy.js
module.exports = {
    local: {
        proxy: 'http://127.0.0.1:12420'
    },
    dev: {
        proxy: 'http://127.0.0.1:12421'
    }
};


// mock/api.js
const {api, resp} = require('apite');
const proxy = require('./proxy');
/**
 * 走代理，修改后可实时生效
 */
api.post('/account/updateInfo', async ctx=>{
    ctx.body = resp.ok();
}, proxy.dev);

/**
 * 不走代理，第三个参数为false即可
 */
api.post('/account/updateInfo', async ctx=>{
    ctx.body = resp.ok();
}, proxy.dev11);
```
