### ISSUE TITLE
详细的文档

### ISSUE THREAD

**Issue by weijianjunwjj** [wangxing218/apite#7]
请问作者大大有没有详细的文档啊？我这边用了您的插件觉得非常好，就是请求接口404，不知道为什么？网上也没找到解决方案。所以不得已请教作者大大404的原因，谢谢！

**Comment by wangxing218** [comment]
请贴一下使用方式！最好是项目源码

**Comment by weijianjunwjj** [comment]
作者大大，我找到原因了。
因为我在api目录下文件定义接口的时候多加了/api,
1.我原来的错误示范：
api.get('/api/json', {
    msg: 'json',
})
2.正确的示范：
api.get('/json', {
    msg: 'json',
})
