### ISSUE TITLE
响应头区分走 mock 数据还是走代理 'Data-From': 'proxy'

### ISSUE THREAD

**Issue by renwangT** [wangxing218/apite#9]
响应头区分走 mock 数据还是走代理 'Data-From': 'proxy'

怎么设置嘞？

在request 中设置 还是 response 中设置？

在request response中都设置了，，返回的 response 中还是 Data-form: apite

**Comment by wangxing218** [comment]
代理设置示例：
api.get(
  '/proxy',
  {},
  {
    proxy: {
      target: 'https://api.weixin.qq.com/cgi-bin/token',
      rewrite: '/proxy',
    },
  },
)

当设置了走代理时，响应头会自动带上'Data-From': 'proxy'。

**Comment by renwangT** [comment]
api.get(
 '/proxy',
 {},
 {
 proxy: {
   target: 'https://xxx.xx.xx.xx:xxxx',   //  我的proxy
   rewrite: '/proxy',
 },
})

我已设置成这样， 接口请求 加上 /proxy/xxxx/xxxx,   请求404？ （我把 vite 里面的 proxy 注释掉了）

**Comment by renwangT** [comment]
mock 数据 /api/user
我的 代理 /api/xxxx  也是 api 开头， 这样怎么区分， 只能把我的代理 更改为 /proxy/xxxx 跟 mock数据的 /api/xxx 区分， 这样子吗？  
我尝试 /myProxy/xxxx  走vite 的代理 也是可以成功请求的，所以问题还是 mock 跟自己的 接口代理 都是 /api/xxx 怎么区分走mock 还是走自己的代理？

上面的设置没有解决我的问题.................

期待你的回复
